version: '3.7'
services:

  mysql:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: r00t
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 5s
      retries: 5

  user-skills:
    image: dboegershausen/user-skills-application:1.0.0
    environment:
      MYSQL_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"