server:
  port: 8081

spring:
  application:
    name: user-skills-application
  profiles:
    default: mysql
  liquibase:
    change-log: classpath:/db/changelog/database-changelog.xml
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC